[tool.poetry]
name = "llm-mlops"
version = "0.1.0"
description = ""
authors = ["tmdqja75 <tmdqja75@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
langchain = "^0.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
